name: "📦 Package & 🚀 Release"

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    name: "Release on tag"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --title "${{ github.ref_name }}" --generate-notes

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci

      - name: Deploy plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSGEO_USER: ${{ secrets.OSGEO_USER }}
          OSGEO_PASSWORD: ${{ secrets.OSGEO_PASSWORD }}
        run: |
          qgis-plugin-ci release "${GITHUB_REF_NAME}" \
          --github-token "${GITHUB_TOKEN}" \
          --osgeo-username "${OSGEO_USER}" \
          --osgeo-password "${OSGEO_PASSWORD}"
